### ISSUE TITLE
Address Deprecated Warning

### ISSUE THREAD

**Issue by nwhobart** [robscott/homebrew-tap#2]
It doesn't seem like this is needed anymore.

https://github.com/robscott/homebrew-tap/blob/7c907b02144dbcbb4118d698db8ea5ff6e26d774/Formula/kube-capacity.rb#L10

```
Warning: Calling bottle :unneeded is deprecated! There is no replacement.
Please report this issue to the robscott/tap tap (not Homebrew/brew or Homebrew/core):
  /usr/local/Homebrew/Library/Taps/robscott/homebrew-tap/Formula/kube-capacity.rb:10
```

**Comment by psnosignaluk** [comment]
Looks like GoReleaser has a fix for this issue: https://github.com/goreleaser/goreleaser/releases/tag/v0.183.0. Looking at the circle-ci config for kubecapacity, it just references the GoReleaser `latest` from their project. See the circleci ref [here](https://github.com/robscott/kube-capacity/blob/bb976088847ed85e4e9694a24aabe896a5ee4276/.circleci/config.yml#L25) and the GoReleaser bash script [here](https://raw.githubusercontent.com/goreleaser/get/master/get).

**Comment by robscott** [comment]
This should be fixed with [v0.6.2](https://github.com/robscott/kube-capacity/releases/tag/v0.6.2), let me know if I missed anything.

**Comment by nwhobart** [comment]
looks great. thanks!

**Comment by psnosignaluk** [comment]
Thank you @robscott
